spring:
  application:
    name: book
  datasource:
    url: jdbc:mysql://localhost/spring_101?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mysecretkeysercretkeysercretkeysercretkey