spring:
  application:
    name: book
  datasource:
    url: jdbc:mysql://localhost/book?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml