spring:
  application:
    name: book
  datasource:
    url: jdbc:mysql://localhost/book?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true